### PR TITLE
Added DescribeDomains documentation to access-basics.md

### PR DESCRIPTION
**Pull request by grabermtw**
Added descriptions and examples of DescribeDomains.

### CODE REVIEW

**Comment by grabermtw** [comment]
I currently have the DescribeDomains explanation in the Time Dimension WMTS section at the end of the document. Not sure if it's preferred to keep it there or to put it in primary WMTS section.

**Review by minniewong — COMMENTED** [review]
Are the sample links supposed to return something useful? I'm getting "Invalid Time Format" for this one. https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/2015-01-26--2022-11-03/250m.xml
And other invalid responses for the other links.

**Comment by grabermtw** [comment]
@minniewong DescribeDomains hasn't yet rolled out into prod, so those links shouldn't work yet. I will test those links again after DescribeDomains is in prod, and only after they are working will this PR be merged.

**Comment by grabermtw** [comment]
DescribeDomains works in GIBS now: https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/MODIS_Terra_CorrectedReflectance_TrueColor/default/250m/all/2015-01-26--2022-11-03.xml

Links have been updated in the documentation, I've confirmed that they all work now.

**Review by jtroberts — APPROVED** [review]

**Review by minniewong — APPROVED** [review]

**Pull request merged**
