### PR TITLE
Overhauled GIS and map library sections

### PR DESCRIPTION
**Pull request by rboller**

### CODE REVIEW

**Review by minniewong — APPROVED** [review]
Looks good to be on the whole! I wondered if some of the images needed image captions e.g. Worldview image snapshot and the OpenLayers with GIBS imagery image.
The intro page needs the two new sections added to it as well.

**Review by Benjaki2 — APPROVED** [review]
Glad to see the markdown `target=blank` syntax getting used. It all looks good to me. My only though is that we should make sure that any unused docs (e.g. `visualization-generation.md `) gets removed before this goes live, so unwanted info isn't found via the search.

**Comment by mcechini** [comment]
Comments/questions/on the gis-usage page:

**Review by mcechini — CHANGES_REQUESTED** [review]
Added my comments above

**Comment by rboller** [comment]
> Looks good to be on the whole! I wondered if some of the images needed image captions e.g. Worldview image snapshot and the OpenLayers with GIBS imagery image.
> The intro page needs the two new sections added to it as well.

Thanks for your suggestions @minniewong, I've just finished making updates which should address them.

**Comment by rboller** [comment]
> Glad to see the markdown `target=blank` syntax getting used. It all looks good to me. My only though is that we should make sure that any unused docs (e.g. `visualization-generation.md `) gets removed before this goes live, so unwanted info isn't found via the search.

@Benjaki2 thanks for your review and agreed about the unused docs... though will defer that kind of update until we do a full review of the entire set.

**Comment by rboller** [comment]
> Comments/questions/on the gis-usage page:
> 
> ### General
> * If the only place we reference using an exported GeoTIFF, maybe you don’t need the snapshot disclaimer at the top.  Regardless, I think the image should be smaller and have a red circle around the camera icon to make it clear how you brought up that dialog

I can still see users trying to use WMTS given that it’s “supported” by GIS clients so think it’s still good to have the disclaimer up front.  I did add a red circle and made the image smaller, though.

> * Perhaps it would be clearer if we renamed the WMS top level layer title so that we had:
>   
>   * WMS Service Name : NASA Global Imagery Browse Services for EOSDIS --> No Change
>   * WMS Top Level Layer Name: NASA_GIBS_EPSG4326_best --> No Change
>   * WMS Top Level Layer Title: NASA Global Imagery Browse Services for EOSDIS --> EPSG:4326 Best Available Visualizations

Fine by me.
 
> ### QGIS
> * If users use the epsg4326 endpoint, can they configure GQIS to send epsg3857 requests? If so, that might be best so that we get the hierarchy.

As I mentioned in GIBS-4828: “I may need to work with @mcechini to see which endpoint the GIS clients are actually requesting… e.g. are they requesting tiles in EPSG:4326 and reprojecting them client-side or are they requesting them in EPSG:3857.  Or does it not matter?”

> * Curious that we’re not seeing the hierarchy when you are “connecting”.  Does that not work anymore?

Ah I think these screen captures were carryovers from earlier when we didn’t have hierarchical WMS.  I've updated them now.

> * Perhaps turn off dark mode so that the legend image text shows up.

Done

> * How does the user know the possible date range? Can you get that in QGIS somehow?

Actually there’s now a nice button to check that next to each temporally-enabled layer.  I’ve added a note and screen caps about it to the docs.

 
> ### ESRI ArcGIS Pro
> * Add link to ArcGIS Pro

Done

> * Ditto to question about epsg4326/3857gibs `

See above

> * Do we want to demonstrate using an exported GeoTIFF?

That should be a really straightforward thing to do so will omit for now.


> ### ESRI ArcGIS/ArcMap
> * Add link to ArcGIS/ArcMap

Done

> * You list the possible URLs in the previous options, but not here.

Per another comment I made in GIBS-4828, we may want to list the WMS endpoints elsewhere in the docs and link to them from here rather than listing them out in each section

> * Perhaps it would be good to show the legend

I’m not sure that I have a working copy of this anymore as it’s relatively deprecated with ArcGIS Pro being the preferred option AFAIK

> * Do we also want to mention that folks can go to the living atlas to find some pre-configured layers?

Same comment above about deprecation but could be good to include in ArcGIS Pro assuming it works there

> * Do we want to demonstrate using an exported GeoTIFF?

See above


> ### ESRI ArcGISOnline
> * You list the possible URLs in the previous options, but not here.

See above

> * The example isn’t showing our hierarchy

The hierarchy doesn't appear to be available in the current version of AGOL

> * After the “Add a Parameter for TIME” comment, perhaps it would be good to say something like “Note: This is an example of time not being fully supported.  Presently you must manually enter your date. “

Done

> * Ditto about the legend
> * For the predefined layers, do you want to show an example of selecting the date. I find it wicked difficult.

Let's see what happens in future versions of AGOL and update our docs at that point

> * Do we want to demonstrate using an exported GeoTIFF?

See above

**Review by mcechini — APPROVED** [review]
Changes look good. A few remaining items to discuss, but we can handle that in the GIBS ticket.

**Pull request merged**
