### PR TITLE
Gibs python use cases

### PR DESCRIPTION
**Pull request by grallewellyn**
Relevant use cases we identified in our ticket https://bugs.earthdata.nasa.gov/projects/GITC/issues/GITC-6202 that I implemented in this PR:
- Converting an image to GeoTIFF. Can just elaborated on existing: https://nasa-gibs.github.io/gibs-api-docs/python-usage/#bulk-downloading-of-gibs-imagery  
- Rasterio gives access to properties of a geospatial raster file. https://github.com/rasterio/rasterio?tab=readme-ov-file#api-overview
- Overlaying. Useful link geopandas: https://geopandas.org/en/stable/docs/user_guide/set_operations.html   And also: https://gis.stackexchange.com/questions/345917/overlay-two-raster-geotiffs-using-rasterio-mask  
- Masking with a shapefile in Rasterio: https://github.com/rasterio/rasterio/blob/main/docs/topics/masking-by-shapefile.rst  
- Reprojection with rasterio: https://github.com/rasterio/rasterio/blob/main/docs/topics/reproject.rst  
- Masks rasterio (including no data mask)- https://github.com/rasterio/rasterio/blob/main/docs/topics/masks.rst . Current example in the docs is only for MODIS Terra: https://nasa-gibs.github.io/gibs-api-docs/python-usage/#using-a-no-data-mask DID NOT IMPLEMENT rasterio.read_masks just returns 255 for all values for our data so this function doesn't work for us 
- Use Pillow to create an animation like we do in this notebook: [https://github.com/EarthDigitalTwin/IDEAS-notebooks/blob/main/Flood_Demo.ipynb](https://raw.githubusercontent.com/EarthDigitalTwin/IDEAS-notebooks/refs/heads/main/Flood_Demo.ipynb)
- Include interactive map examples: cartopy
https://scitools.org.uk/cartopy/docs/v0.15/examples/wmts.html  ipyleaflet
https://ipyleaflet.readthedocs.io/en/latest/layers/wms_layer.html (WAS ALREADY IMPLEMENTED) folium
https://python-visualization.github.io/folium/latest/user_guide/raster_layers/wms_tile_layer.html 

Other notes: 

I verified that mapping wmts raster data with cartopy gives the same result as creating the jpg with gdal_translate from the .xml file. 

Unfortunately, the animated gif example cannot be rendered in the docs page like the existing ipyleaflet example

I know you can’t see the changes from Git in this PR, but I like ReviewNB for looking at changes to notebooks 

@jtroberts I wasn't sure who else to add as a reviewer for this PR

### CODE REVIEW

**Comment by grallewellyn** [comment]
We decided in the GITC standup meeting that Alex and Matt would be the best to review

**Comment by jtroberts** [comment]
> `rasterio.open` gives me height, width as 512 x 512 which is different than the 163840 x 81920 you said it should be.

That makes sense given that you specified HEIGHT=512&WIDTH=512. I would change WIDTH=1024 to keep the image in the correct proportion. In that case, the expected output size should be 1024 x 512.

> It is EPSG:3857 to EPSG:9921

How about we use EASE Grid instead since it is a more common equal-area global projection? So EPSG:3857 to EPSG:6933.

**Comment by grallewellyn** [comment]
> That makes sense given that you specified HEIGHT=512&WIDTH=512. I would change WIDTH=1024 to keep the image in the correct proportion. In that case, the expected output size should be 1024 x 512.

Okay made that change

Okay, I changed to EPSG:6933 and this is the reprojected image
Screenshot 2024-12-12 at 11 37 56 AM

**Review by jtroberts — APPROVED** [review]
Changes look good to me! My last suggestion is to render that reprojected image in the notebook for reference but not a big deal.

**Comment by grallewellyn** [comment]
Added showing the reprojected image to the notebook

**Pull request merged**
